# Arithmetic Operations on Numpy Array

In [ ]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a+2

array([3, 4, 5, 6])

In [6]:
a-2         #2 is subtracted from original array

array([-1,  0,  1,  2])

In [7]:
b=a-2
print(b)

[-1  0  1  2]


In [8]:
a*2

array([2, 4, 6, 8])

In [9]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [10]:
a**2


array([ 1,  4,  9, 16])

In [11]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [12]:
a=np.array([1,2,3,4])  #Dimensions must be same 
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [14]:
#Trignometric Functions
#np.sin(a)
np.sin(a[0])

0.8414709848078965

In [ ]:
# More Funtions on Numpy array
# https://numpy.org/doc/stable/reference/routines.math.html

# Linear Algebra

In [6]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],[8,9,10,11]])     2X4 Matrix
print(a)
b=np.array([[4,1],[5,3],[6,8],[3,2]])   4X4 Matrix
print(b)

[[ 1  2  3  4]
 [ 8  9 10 11]]
[[4 1]
 [5 3]
 [6 8]
 [3 2]]


In [7]:
#Matrix Multiplication:
np.matmul(a,b)   # mat for matrix and mul for multiplication

array([[ 44,  39],
       [170, 137]])

In [8]:
# Determinant of a matrix
a = np.array([[1,2,6],[7,8,9],[4,5,6]])
np.linalg.det(a)   # linearalgebra determinant


9.000000000000005

In [9]:
#Eigen Value of square matrix
a = np.array([[1,6],[8,9]])
np.linalg.eig(a)

EigResult(eigenvalues=array([-3., 13.]), eigenvectors=array([[-0.83205029, -0.4472136 ],
       [ 0.5547002 , -0.89442719]]))

In [10]:
# For More linalg functions:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [11]:
a = np.array([[3,6,2],[4,5,1]])
a

array([[3, 6, 2],
       [4, 5, 1]])

In [12]:
# Find minimum
np.min(a)

1

In [15]:
# Row wise min
np.min(a,axis=1)   #gives min element of each row  #for row use axis =1

array([2, 1])

In [16]:
# Column wise min
np.min(a, axis=0) #gives min element of each Column  #for Column use axis =0

array([3, 5, 1])

In [17]:
# Similarly Max
np.max(a)

6

In [18]:
# Row wise max
np.max(a, axis=1)

array([6, 5])

In [19]:
# Column wise max
np.max(a, axis=0)

array([4, 6, 2])

In [20]:
# Sum of elements
np.sum(a)

21

In [21]:
#Can you use axis for sum?
#for rows
np.sum(a, axis = 1)

array([11, 10])

In [22]:
#for Column
np.sum(a, axis = 0)

array([ 7, 11,  3])

In [23]:
# mean 
a = np.array([[1,6,9],[4,5,1]])
np.mean(a)

4.333333333333333

In [24]:
# median
a = np.array([[1,6,9],[4,5,1]])
np.median(a)             #on sorting we get 1,1,4,5,6,9 i.e (4+5)/2

4.5

In [25]:
# standard deviation   #S.D=root variance 
np.std(a)

2.8087165910587863

In [26]:
# Variation
np.var(a)

7.888888888888889

# Linear Equations


In [27]:
# 4x + 5y = 13
# 5x - 3y = 7
coeff1 = np.array([[4,5],[5,-3]])
coeff2 = np.array([13,7])

np.linalg.solve(coeff1, coeff2)      #x=2 y=1 comes as result

array([2., 1.])

In [ ]:
# More Statistical Funcions

# https://numpy.org/doc/stable/reference/routines.statistics.html