In [1]:
print('hi')

hi


# Heading

In [1]:
import numpy as np

In [43]:
a = np.array([1,2,3,4])
#print(a)
# To update 
# a[0]=15
# print(a)

[15  2  3  4]


In [3]:
a = np.array([1,2,3,4])
print(a[-1])

4


In [6]:
a = np.array([1,2,3,4])  #4 not included
print(a[0:3])

[1 2 3]


In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #it will not print 0
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
#Get Dimension 
#For this, we have an attribute to find the dimension of an array

#Note the difference between Attribute and Function .In Attribute no need to put Parenthesis
#a.ndim

b.ndim     #b is 2D array    



2

In [1]:
#Get Shape
import numpy as np
a = np.array([1,2,3,4])
a.shape
#b.shape      #since 2rows and 3 columns in b

(4,)

In [2]:
#reshape
import numpy as np

x=np.array([1,2,3,4,5,6])
print(x)

# y=x.reshape(2,3)
# print(y)

# y=x.reshape(3,2)
# print(y)

y=x.reshape(6,1)
print(y)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
#Get Type
# a.dtype #dtype means datatype
b.dtype

dtype('float64')

In [26]:
#Get Size
b.itemsize       #64bits =8bytes
# a.itemsize    32 bits=4bytes 

8

In [28]:
#Get total Size
# a.nbytes     #in a we have 4 elements and each element is of 4 bytes ,so 4*4bytes=16
b.nbytes   # 6*8=48 since 6 elements and each of 8 bytes 

48

In [30]:
#Get number of elements
# a.size
b.size

6

# Acessing/Changing Specific Elements,Rows,Columns,etc

In [34]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
#Get specfic element[r,c]
a[1,5]

13

In [36]:
#Get specific row

# a[1,:]     #it accesses 1st row only
b[2,:]          #it accesses 2nd row only



array([ 8,  9, 10, 11, 12, 13, 14])

In [38]:
#Get specific column
a[:,2] #in both rows see the 2nd column it is 3,10
#a[:,5]

array([ 6, 13])

In [39]:
#[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [40]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
#Update an element 
a[1,5]=27
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 27 14]]


In [47]:
#Update elements
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a[:,2] = 5        #In 2nd column update 5,5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [49]:
a[1:,] = 21       #In 2nd row update all elements as 21
print(a)

[[ 1  2 18  4  5  6  7]
 [21 21 21 21 21 21 21]]


In [48]:
#Update elements
a[:,2] = [18,19]       #In 2nd column update 18,19
print(a)

[[ 1  2 18  4  5  6  7]
 [ 8  9 19 11 12 13 14]]


# 3D Array

In [50]:
c =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #four 1D array combines to two 2D array
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
b =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #four 1D array combines to two 2D array
print(b[0,:,:])   #1st is plane,2nd is row,3rd is column

[[1 2]
 [3 4]]


# Initializing Different Types of Arrays 


In [56]:
#All 0s matrix
# np.zeros((2,3))    default is double  and here we are giving size 
#np.zeros((2,3),dtype='int32')  #to cobvert it to int 
np.zeros((2,3,3),dtype='int32')    # 2 plan and 3X3 matrix 


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [58]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')  #4 plane and 2X2 matrix

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [59]:
#Any other number 
np.full((2,2),27)

array([[27, 27],
       [27, 27]])

In [63]:
print(a)
#Any other number(full_like)
np.full(a,4)


[[ 1  2 18  4  5  6  7]
 [21 21 21 21 21 21 21]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

# Most important Random decimal numbers

In [68]:
#Random decimal numbers
np.random.rand(4,2)  #rand gives normal distribution means the range between 0&1(any random value)

array([[0.69743451, 0.78947407],
       [0.19891519, 0.38894745],
       [0.38038342, 0.84934291],
       [0.43989818, 0.85713325]])

In [69]:
#Random Integer Values
np.random.randint(-4,8,size=(3,3))     #it generates random values between -4 & 8 and stores it in 3X3 matrix

array([[-2,  0, -4],
       [ 3,  1,  7],
       [-3, -2,  1]])

In [70]:
#The identity matrix
np.identity(5) #default is float 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Copy and Other Operations

In [71]:
a=np.array([1,2,3])
b=a
b[0]=100

print(a)

[100   2   3]


In [72]:
a=np.array([1,2,3])
b=a.copy()       #by copying a into b only , b will become new array
b[0]=100

print(b)
print(a)

[100   2   3]
[1 2 3]
