# Arithmetic Operations on Numpy Array

In [ ]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a+2

array([3, 4, 5, 6])

In [6]:
a-2         #2 is subtracted from original array

array([-1,  0,  1,  2])

In [7]:
b=a-2
print(b)

[-1  0  1  2]


In [8]:
a*2

array([2, 4, 6, 8])

In [9]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [10]:
a**2


array([ 1,  4,  9, 16])

In [11]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [12]:
a=np.array([1,2,3,4])  #Dimensions must be same 
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [14]:
#Trignometric Functions
#np.sin(a)
np.sin(a[0])

0.8414709848078965